'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace FileManager
    
    Partial Public Class ChooserPage
        
        '''<summary>
        '''fileManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileManager1 As Global.GleamTech.FileUltimate.AspNet.WebForms.FileManagerControl
        
        '''<summary>
        '''fileManager2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileManager2 As Global.GleamTech.FileUltimate.AspNet.WebForms.FileManagerControl
        
        '''<summary>
        '''fileManager3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileManager3 As Global.GleamTech.FileUltimate.AspNet.WebForms.FileManagerControl
        
        '''<summary>
        '''fileManager4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileManager4 As Global.GleamTech.FileUltimate.AspNet.WebForms.FileManagerControl
        
        '''<summary>
        '''fileManager5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileManager5 As Global.GleamTech.FileUltimate.AspNet.WebForms.FileManagerControl
        
        '''<summary>
        '''fileManager6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileManager6 As Global.GleamTech.FileUltimate.AspNet.WebForms.FileManagerControl
        
        '''<summary>
        '''fileManager7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fileManager7 As Global.GleamTech.FileUltimate.AspNet.WebForms.FileManagerControl
    End Class
End Namespace
