//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GleamTech.FileUltimateExamples.WebForms.CS.FileManager {
    
    
    public partial class ChooserPage {
        
        /// <summary>
        /// fileManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GleamTech.FileUltimate.FileManager fileManager1;
        
        /// <summary>
        /// fileManager2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GleamTech.FileUltimate.FileManager fileManager2;
        
        /// <summary>
        /// fileManager3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GleamTech.FileUltimate.FileManager fileManager3;
        
        /// <summary>
        /// fileManager4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GleamTech.FileUltimate.FileManager fileManager4;
        
        /// <summary>
        /// fileManager5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GleamTech.FileUltimate.FileManager fileManager5;
        
        /// <summary>
        /// fileManager6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GleamTech.FileUltimate.FileManager fileManager6;
        
        /// <summary>
        /// fileManager7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::GleamTech.FileUltimate.FileManager fileManager7;
    }
}
